export enum Resource {
    INSPECTIONS = 'inspections',
    ASSETS = 'assets',
    REPORTS = 'reports',
    CUSTOMERS = 'customers',
    GROUPS = 'groups',
    USERS = 'users',
    INVOICES = 'invoices',
    CHECKLISTS = 'checklists',
    PERMISSIONS = 'permissions',
    CLIENTS = 'clients',
    PUMP_BRANDS = 'pump-brands',
    PUMPS = 'pumps',
    ASSET_TYPES = 'asset-types',
    PHOTOS = 'photos',
    COMPANIES = 'companies',
    SERVICES = 'services',
    CHECKLIST_TEMPLATES = 'checklist-templates',
    INSPECTION_CHECKLISTS = 'inspection-checklists',
    LOGS = 'logs',
    PACKAGES = 'packages',
  }